platform :ios, '11.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MinersWorldCoin' do
  config = use_native_modules!

  use_frameworks! :linkage => :static

  # Let React Native handle its own pods
  use_native_modules!

  # Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  # Vector icons (manual is fine)
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'MinersWorldCoinTests' do
    inherit! :complete
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end